### ISSUE TITLE
Auth command for redis instances?

### ISSUE THREAD

**Issue by ciarans** [eleme/corvus#105]
Great software, Does corvus support redis AUTH for instances or does it just accept a master like twemporxy? i.e.

myredis.com:6379 - AUTH mypass
myredis2.com:6379 - AUTH mypass2

**Comment by doyoubi** [comment]
Unlike twemproxy, corvus is based on the [official redis cluster](https://redis.io/topics/cluster-tutorial). It acts as a stateless proxy and clients can treat the whole redis cluster as a single redis instance by sending redis request to corvus.
In fact corvus doesn't even support `AUTH` for redis. That means when forwarding requests to redis corvus can't send a `AUTH` command to redis first.
However, corvus do have its own `AUTH` command. You can set the `requirepass` in corvus config file to force client connection to send a `AUTH` first.

**Comment by ciarans** [comment]
@doyoubi thanks for getting back to me. My app does not send it to corvus, however my ec2 instance running redis needs the auth command.

Im trying to use corvus as a redis cache for Google PageSpeed. Google PageSpeed does not support AUTH, so my idea was to use corvus, without auth to connect my Redis instances that require auth.

```nginx
#Corvus without Auth
pagespeed RedisServer "127.0.0.1: 12345";
```

I was thinking that I could then receive the command via corvus and then auth into my ec2 instance.

```
corvus --> AUTH --> REDIS_EC2
```

Is this possible? Thanks for your help

**Comment by doyoubi** [comment]
Sorry to say that corvus can't send `AUTH` to redis.

**Comment by ciarans** [comment]
Ok, Thanks fro you help

**Comment by georgasa** [comment]
Hello @doyoubi , Do you have any plans to support AUTH in corvus? This would be strictly needed if we need to use Corvus in front of password protected DBs...
Thanks,
Tolis

**Comment by doyoubi** [comment]
@georgasa Sorry there's no plan for that.

**Comment by georgasa** [comment]
@doyoubi Thanks for the fast response. And may I ask why this excellent software doesn't support this trivial command? Is there any specific complexity to send Auth command right after the cluster is known to Corvus by the cluster nodes command? The lack of this command makes Corvus unusable for the info password protected Redis. In my case, corvus is on application VM while the Redis cluster is located on totally different VMs.

Thank you,
Tolis

**Comment by doyoubi** [comment]
@georgasa Well, I have to say that we will not add any feature to corvus any more.
This project is mainly maintained by eleme infrastructure team and there' no enough resource to keep implementing new features currently even though we're still massively using it.
For me the C language is super hard and time consuming to add new stuff without breaking existing code compared to some other modern system programming languages. And the backend connection on corvus does not have any existing `context` or `state` which AUTH will need. We would like to leave corvus in the current stable state.
So, sorry for that. And I recommand disabling the password if possible because it's just not that safe to rely on password if someone is able to access your redis directly.
